name: Latest readme blog post listing workflow
on:
    schedule: # Run workflow automatically
        - cron: '0 0 * * *'  # Fixed: was '0 0 * **', should be '0 0 * * *'
    workflow_dispatch: # Run workflow manually
permissions:
    contents: write # To write the generated contents to the readme
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Pull in "Dean's List" posts
              uses: gautamkrishnar/blog-post-workflow@v1
              with:
                  comment_tag_name: "DEANS_LIST"
                  commit_message: 'Updated readme with the latest deans list data'
                  feed_list: 'https://deancochran.github.io/rss.xml'
